name: meditation_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: True
  ios: True
  image_path: "assets/images/meditation-types/Energy.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.svg
    - assets/images/Lotus.png
    - assets/images/meditation-types/Focus.png
    - assets/images/meditation-types/Kindness.png
    - assets/images/meditation-types/Energy.png
    - assets/images/meditation-types/Focus_bg.png
    - assets/images/meditation-types/Kindness_bg.png
    - assets/images/meditation-types/Energy_bg.png
